name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Generate GraphQL code
        run: |
          curl --fail-with-body -sSL https://docs.github.com/public/fpt/schema.docs.graphql -o gql/schema.graphql
          go generate ./gql/...
      - uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
          release_tag: ${{ github.event.inputs.release_tag || github.ref_name }}
